inherit_gem:
  ws-style:
    - default.yml

AllCops:
  # Specify your target Ruby version here (only major/minor versions):
  TargetRubyVersion: 2.4
  Exclude:
    - '*.gemspec'
    - 'bin/**/*'
    - 'examples/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'

Style/FileName:
  Enabled: false
